stages:
  - build
  - test

build:
  stage: build
  script:
    - 'dotnet publish -c Release -o ./publish'
    - 'cd Collibri/ClientApp'
    - 'npm install'
    - 'npm run build'
    - 'cd ../..'
  artifacts:
    paths:
      - publish/
      - Collibri/ClientApp/build/

test:
  stage: test
  script:
    - 'dotnet test Collibri.Tests/Collibri.Tests.csproj --results-directory ./testresults'
  artifacts:
    reports:
      junit: ./testresults/*.xml
    when: always