stages:
  - build
  - test
  - deploy

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_script:
  - 'dotnet restore'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'
  artifacts:
    paths:
      - bin/
      - obj/

test:
  stage: test
  script:
    - 'dotnet test --no-restore --verbosity normal'
  artifacts:
    when: always
    reports:
      junit: TestResults/*.xml

deploy:
  stage: deploy
  script:
    - echo "Deploy your application here"
  only:
    - master
