stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: 'Collibri'
  BUILD_CONFIGURATION: 'Release'
  DOTNET_CORE_SDK_VERSION: '7.0' # Specify the version you're using

build:
  stage: build
  tags: 
    - amma
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_CORE_SDK_VERSION}
  script:
    - 'dotnet build'

test:
  stage: test
  tags: 
    - amma
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_CORE_SDK_VERSION}
  script:
    - 'dotnet test ${PROJECT_NAME}.Tests --no-build --verbosity normal'
  artifacts:
    when: always
    reports:
      junit: TestResults/**/*.xml
    expire_in: 1 week

deploy_staging:
  stage: deploy
  tags: 
    - amma
  script:
    - 'echo "Deploy to staging environment"'
    # Add deployment scripts for staging
  only:
    - develop

deploy_production:
  stage: deploy
  tags: 
    - amma
  script:
    - 'echo "Deploy to production environment"'
    # Add deployment scripts for production
  only:
    - main # Assuming 'main' is your default production branch
  when: manual # Require manual trigger for production deployment
