stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: 'Collibri'
  BUILD_CONFIGURATION: 'Release'
  DOTNET_CORE_SDK_VERSION: '7.0'

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_CORE_SDK_VERSION}
  script:
    - 'dotnet build ${PROJECT_NAME} --configuration ${BUILD_CONFIGURATION} --no-restore'
  artifacts:
    paths:
      - '**/bin/${BUILD_CONFIGURATION}/**'
    expire_in: 1 hour

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_CORE_SDK_VERSION}
  script:
    - 'dotnet test ${PROJECT_NAME}.Tests --no-build --verbosity normal'
  artifacts:
    reports:
      junit: '**/TestResults/**/*.xml'
    expire_in: 1 week

deploy_staging:
  stage: deploy
  script:
    - 'echo "Deploy to staging environment"'
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - 'echo "Deploy to production environment"'
  only:
    - main
  when: manual
