stages:
  - build
  - test

build_react:
  stage: build
  image: node:20
  script:
    - cd Collibri
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - Collibri/build

build_dotnet:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet restore
    - dotnet build --no-restore -c Release
  artifacts:
    paths:
      - bin/

test_app:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test

