name: CI/CD Pipeline

on: [push]

env:
  DOTNET_CORE_SDK_VERSION: '3.1'
  NODE_VERSION: '14'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_SDK_VERSION }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install frontend dependencies
        run: npm install --prefix frontend

  build-backend:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Backend
        run: |
          cd backend
          dotnet restore
          dotnet build -c Release --no-restore
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

  build-frontend:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

  unit-tests:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Unit Tests
        run: |
          cd backend
          dotnet test

  deploy-job:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
