stages:
  - build
  - test

before_script:
  - 'dotnet --version'

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet restore /Collibri.Tests
    - dotnet build /Collibri.Tests --no-restore'
  only:
    - main

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test /Collibri.Tests --no-restore --verbosity normal
